title:                Polymer Digital
url:                  "https://polymerdigital.com"
collections_dir:      _collections
layouts_dir:          _html/layouts
includes_dir:         _html/includes
plugins_dir:          _plugins

# Collections
collections:
  utilities:
    permalink:         :path/
    output:            true
  pages:
    permalink:         :path/
    output:            true
    layout:            page
  articles:
    permalink:         /articles/:path/
    output:            true
  services:
    permalink:         /what-we-do/:path/
    layout:            service
    output:            true
  work:
    permalink:         /work/:path/
    output:            true

# Defaults
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "work"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate-v2 

exclude: [pull_request_template.md, README.md, Gemfile, Gemfile.lock, package.json, node_modules, gulpfile.js, yarn.lock, .jshintrc, package-lock.json, netlify.toml, vendor]

# Pagination Settings
pagination:
  enabled: true
  debug: true
  collection: 'articles'
  per_page: 6
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true