[build]
  publish = '_site'
  command = 'gulp build'


[context.deploy-preview]
  command = 'cat > _config.staging.yml && printf "url: $DEPLOY_PRIME_URL" > _config.staging.yml && gulp build-staging'


[context.branch-deploy]
  command = 'cat > _config.staging.yml && printf "url: $DEPLOY_PRIME_URL" > _config.staging.yml && gulp build-staging'
