[build]
  publish = '_site'
  command = 'gulp build'


[context.deploy-preview]
  command = 'sed -i -e "s%url: \"http://localhost:4000\"%url: \""$DEPLOY_PRIME_URL"\"%" _config.yml && gulp build'


[context.branch-deploy]
  command = 'sed -i -e "s%url: \"http://localhost:4000\"%url: \""$DEPLOY_PRIME_URL"\"%" _config.yml && gulp build'
