[build]
  publish = '_site'
  command = 'gulp build'


[context.deploy-preview]
  command = 'cat > _config.staging.yml && printf "url: $DEPLOY_PRIME_URL" > _config.staging.yml && gulp build-staging


[context.branch-deploy]
  command = 'sed -i -e "s/https:\/\/polymerdigital.com/$DEPLOY_PRIME_URL/" _config.yml && gulp build'
