---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _work
  label: Work
  create: all
  match: "**/*"
  path: _collections/_work
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
  path: _collections/_services
- type: directory
  path: _articles
  label: Articles
  create: all
  match: "**/*"
  path: _collections/_articles
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
  path: _collections/_pages
- type: directory
  path: _utilities
  label: Utilities
  create: all
  match: "**/*"
  hidden: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
